name = "IPORA PIXELMON"
author = "Admin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e64f060bbbe9b4bcf087ce2d988ef3f28b7a34710111d0f743cd3ecd5a7a8c57"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
