name = "IPORA PIXELMON"
author = "Admin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "171743612c0aa4d11a4ba733e0e9863e2905d5e29ca44efb23d1dac0570a249d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
