name = "IPORA PIXELMON"
author = "Admin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32c9adad386f8f88a4f6513701234285a420c5e2353004719a9039cf61f14ef6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
